### PR TITLE
Automatic recon of files, folders, headers, and some language probing

### PR DESCRIPTION
**Pull request by dantt**
Probes files and folders, GETs headers, tries to guess PHP and Python. Progresses #3 

I tried to keep prints consistent, but I don't really like the output. We might improve it in the future

### CODE REVIEW

**Comment by thebabush** [comment]
Just one thing: from personal experience I know that sitemap.xml can be huge, so I'm not sure it's a good idea to print it. Any thoughts?

**Comment by dantt** [comment]
To improve output, I would hardly print any file content (besides headers) on screen.
We could just dump all files found to file.
Currently we have  ============= HEADER ============ for each file for which we want content, and also for sections. Currently it looks like:
============== AUTO RECON ============
============== robots.txt ==============
*** Getting https://www.github.com/robots.txt... 200
[CONTENT]
============================== sitemap.xml ==============================
*** Getting https://www.github.com/sitemap.xml... 406
============================== Folder probing ==============================
*** Headding https://www.github.com/static/... 301
*** Headding https://www.github.com/img/... 301
*** Headding https://www.github.com/imgs/... 301
*** Headding https://www.github.com/images/... 301
*** Headding https://www.github.com/css/... 301
*** Headding https://www.github.com/js/... 301
*** Headding https://www.github.com/.git/... 301
*** Headding https://www.github.com/.svn/... 301
============================== Path traversal ==============================

etc.

It doesn't look good. I'll keep the ===== HEADERS ===== just for sections, and then a single row for each probed file. Found files can be saved in a folder. So it would look like:

 ============================== AUTO RECON  ==============================
*** Getting https://www.github.com/robots.txt... 200
*** Getting https://www.github.com/sitemap.xml... 406
============================== Folder probing ==============================
*** Headding https://www.github.com/static/... 301
*** Headding https://www.github.com/img/... 301
*** Headding https://www.github.com/imgs/... 301
*** Headding https://www.github.com/images/... 301
*** Headding https://www.github.com/css/... 301
*** Headding https://www.github.com/js/... 301
*** Headding https://www.github.com/.git/... 301
*** Headding https://www.github.com/.svn/... 301

Etc.
What do you think?

B/c also robots.txt can be HUUUUGE.

**Comment by thebabush** [comment]
Maybe we can do something like printing the first ~N lines? It can be useful for a fast robots/sitemap inspection.

**Comment by dantt** [comment]
Yes it would work and it's a good idea.

Doesn't help with the output however - but I guess we can think about it later.
I'll fix this

**Comment by thebabush** [comment]
Yep, we can figure out the output style later.

**Comment by dantt** [comment]
Should be done now.
Sorry I was busy and this slipped my mind.

**Comment by thebabush** [comment]
Looks good, thanks :)

**Pull request merged**
